### ISSUE TITLE
Upgrade base image

### ISSUE THREAD

**Issue by SuperSandro2000** [metabrainz/base-image#1]
The base image is quite old already and I would suggest updating it to at least version 0.10.2 or even 0.11 if we are ready for 18.04 LTS. The changelog can be found here https://github.com/phusion/baseimage-docker/releases .

When I fixed the building of the depending docker files I would be willing to test basic functionality if the images build and the resulting musicbrainz server shows some sites, search, etc.

What do you thing about this?

**Comment by dns53** [comment]
Can we change this to phusion/baseimage:master
I am building this on a raspberry pi and master has amd64, arm and arm64

**Comment by SuperSandro2000** [comment]
Master is on Ubuntu bionic and most stuff is still based on xenial sadly. This would definitely require more testing. I would do that with some instructions is there is interest from the developers.

**Comment by mwiencek** [comment]
There's a focal branch + tag here using 20.04 now (though it won't be merged to master until all of our containers use it -- only a few do at present).
